<template>
  <!-- ======= Footer ======= -->  
  <hr>
  <footer id="footer" class="footer parallax" style="background-color: white; color: black; padding: 200px 0; position: relative; overflow: hidden;">
    <div class="container" style="max-width: 1400px;">
      <div class="row">
        <!-- Şirket Logosu ve Sosyal Medya Section -->
        <div class="col-lg-4 col-md-6 mb-4">
          <h3 style="font-size: 2.2rem; color: #4f4f4f;">Sosyal Medya</h3>
          <ul style="list-style: none; padding: 0;">
            <li style="margin-bottom: 15px;">LinkedIn</li>
            <li style="margin-bottom: 15px;">GitHub</li>
            <li style="margin-bottom: 15px;">Instagram</li>
            <li style="margin-bottom: 15px;">YouTube</li>
            <li style="margin-bottom: 15px;">X</li>
          </ul>
        </div>

        <!-- Kurumsal Section -->
        <div class="col-lg-4 col-md-6 mb-4">
          <h3 style="font-size: 2.2rem; color: #4f4f4f;">Kurumsal</h3>
          <ul style="list-style: none; padding: 0;">
            <li style="margin-bottom: 15px;">Hakkımızda</li>
            <li style="margin-bottom: 15px;">Kariyer</li>
            <li style="margin-bottom: 15px;">İletişim</li>
          </ul>
        </div>

        <!-- Gizlilik ve Güvenlik Section -->
        <div class="col-lg-4 col-md-6 mb-4">
          <h3 style="font-size: 2.2rem; color: #4f4f4f;">Gizlilik ve Güvenlik</h3>
          <ul style="list-style: none; padding: 0;">
            <li style="margin-bottom: 15px;">Gizlilik İlkeleri</li>
            <li style="margin-bottom: 15px;">Çerez Aydınlatma Metni</li>
            <li style="margin-bottom: 15px;">Kişisel Verilerin Korunması</li>
            <li style="margin-bottom: 15px;">KVKK Başvuru Formu</li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- ======= Footer Bottom ======= -->
  <div style="background-color: black; padding: 20px 0;">
    <div style="text-align: center;">
      <strong style="font-size: 1rem; color: white;">2024 &copy; Tüm Hakları Saklıdır</strong>
    </div>
  </div>
</template>

<style scoped>
.footer {
  color: black;
  background: linear-gradient(to bottom, #ffffff, #dddddd);
  background-position: center;
  min-height: 600px;
  transform: translateZ(0);
  position: relative;
}
.footer h3 {
  color: #4f4f4f;
}
.footer ul li {
  font-size: 1.5rem;
  cursor: pointer;
}
.footer ul li:hover {
  text-decoration: underline;
}
</style>
